"""fase-1: faturamento_notas, medicao_records, usinagem_registros, operacoes_producao, registros_producao

Revision ID: b1acbb622e52
Revises: 328569894525
Create Date: 2026-06-17 02:42:44.469559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1acbb622e52'
down_revision = '328569894525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturamento_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('emissao', sa.Date(), nullable=False),
    sa.Column('contrato', sa.String(length=80), nullable=True),
    sa.Column('orgao', sa.String(length=120), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('bruto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('inss', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ir', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('iss', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('liquido', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('recebido', sa.Boolean(), nullable=True),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'nr', name='uq_faturamento_org_nr')
    )
    op.create_table('usinagem_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=40), nullable=True),
    sa.Column('data_operacao', sa.Date(), nullable=True),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('motorista', sa.String(length=120), nullable=True),
    sa.Column('peso_bruto', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tara', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('peso_liquido', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('regiao', sa.String(length=60), nullable=True),
    sa.Column('contrato', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'ticket', name='uq_usinagem_org_ticket')
    )
    op.create_table('medicao_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('gerado_por', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('contrato', sa.String(length=80), nullable=True),
    sa.Column('periodo', sa.String(length=40), nullable=True),
    sa.Column('docx_r2_key', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gerado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operacoes_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('modo', sa.String(length=10), nullable=True),
    sa.Column('data_operacao', sa.Date(), nullable=False),
    sa.Column('ticket_inicio', sa.Integer(), nullable=True),
    sa.Column('ticket_fim', sa.Integer(), nullable=True),
    sa.Column('total_caminhoes', sa.Integer(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('motorista', sa.String(length=120), nullable=True),
    sa.Column('entrada', sa.String(length=10), nullable=True),
    sa.Column('saida', sa.String(length=10), nullable=True),
    sa.Column('tara', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('peso', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('regiao', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes_producao.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_producao')
    op.drop_table('operacoes_producao')
    op.drop_table('medicao_records')
    op.drop_table('usinagem_registros')
    op.drop_table('faturamento_notas')
    # ### end Alembic commands ###
